### ISSUE TITLE
Generate tar.gz release

### ISSUE THREAD

**Issue by oblute** [NOAA-ORR-ERD/hazpy.unit_conversion#1]
Can you generate a tar.gz release for this package? I'm trying to build pyGNOME for the conda forge. unit_conversion is a dependency, so needs to be built first before. Thanks!

**Comment by ChrisBarker-NOAA** [comment]
I take it you found:
 https://github.com/NOAA-ORR-ERD/PyNUCOS

and:

https://anaconda.org/conda-forge/pynucos

**Comment by ChrisBarker-NOAA** [comment]
@oblute:

If you do make a conda-forge recipe, be sure to include me as a maintainer, and I'm glad to help.

Also: be sure to ping us on the py_gnome repo before you build the "final" version -- we can make sure to get a recent version. -- we're doing a lot of active development in house, and often dont get around to pushing new versions to gitHub.
